2016/09/08 15:45:27 [error] [exception.CException] exception 'CException' with message 'CAssetManager.basePath "/Applications/XAMPP/xamppfiles/htdocs/blog/assets" is invalid. Please make sure the directory exists and is writable by the Web server process.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CAssetManager.php:138
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CAssetManager.php(123): CAssetManager->setBasePath('/Applications/X...')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CAssetManager.php(217): CAssetManager->getBasePath()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/zii/widgets/CListView.php(217): CAssetManager->publish('/Applications/X...')
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CBaseController.php(147): CListView->init()
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CBaseController.php(180): CBaseController->createWidget('zii.widgets.CLi...', Array)
#5 /Applications/XAMPP/xamppfiles/htdocs/blog/protected/views/post/index.php(9): CBaseController->widget('zii.widgets.CLi...', Array)
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CBaseController.php(126): require('/Applications/X...')
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CBaseController.php(95): CBaseController->renderInternal('/Applications/X...', Array, true)
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(869): CBaseController->renderFile('/Applications/X...', Array, true)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(782): CController->renderPartial('index', Array, true)
#10 /Applications/XAMPP/xamppfiles/htdocs/blog/protected/controllers/PostController.php(136): CController->render('index', Array)
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): PostController->actionIndex()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#13 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#14 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilter.php(40): CFilterChain->run()
#15 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#16 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#17 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#18 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(291): CFilterChain->run()
#19 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#20 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('')
#21 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('')
#22 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#23 /Applications/XAMPP/xamppfiles/htdocs/blog/index.php(11): CApplication->run()
#24 {main}
REQUEST_URI=/blog/
---
2016/09/08 15:45:46 [error] [exception.CException] exception 'CException' with message 'CAssetManager.basePath "/Applications/XAMPP/xamppfiles/htdocs/blog/assets" is invalid. Please make sure the directory exists and is writable by the Web server process.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CAssetManager.php:138
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CAssetManager.php(123): CAssetManager->setBasePath('/Applications/X...')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CAssetManager.php(217): CAssetManager->getBasePath()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/zii/widgets/CListView.php(217): CAssetManager->publish('/Applications/X...')
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CBaseController.php(147): CListView->init()
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CBaseController.php(180): CBaseController->createWidget('zii.widgets.CLi...', Array)
#5 /Applications/XAMPP/xamppfiles/htdocs/blog/protected/views/post/index.php(9): CBaseController->widget('zii.widgets.CLi...', Array)
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CBaseController.php(126): require('/Applications/X...')
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CBaseController.php(95): CBaseController->renderInternal('/Applications/X...', Array, true)
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(869): CBaseController->renderFile('/Applications/X...', Array, true)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(782): CController->renderPartial('index', Array, true)
#10 /Applications/XAMPP/xamppfiles/htdocs/blog/protected/controllers/PostController.php(136): CController->render('index', Array)
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): PostController->actionIndex()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#13 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#14 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilter.php(40): CFilterChain->run()
#15 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#16 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#17 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#18 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(291): CFilterChain->run()
#19 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#20 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('')
#21 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('')
#22 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#23 /Applications/XAMPP/xamppfiles/htdocs/blog/index.php(11): CApplication->run()
#24 {main}
REQUEST_URI=/blog/
---
2016/09/08 15:46:06 [error] [exception.CException] exception 'CException' with message 'CAssetManager.basePath "/Applications/XAMPP/xamppfiles/htdocs/blog/assets" is invalid. Please make sure the directory exists and is writable by the Web server process.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CAssetManager.php:138
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CAssetManager.php(123): CAssetManager->setBasePath('/Applications/X...')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CAssetManager.php(217): CAssetManager->getBasePath()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/zii/widgets/CListView.php(217): CAssetManager->publish('/Applications/X...')
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CBaseController.php(147): CListView->init()
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CBaseController.php(180): CBaseController->createWidget('zii.widgets.CLi...', Array)
#5 /Applications/XAMPP/xamppfiles/htdocs/blog/protected/views/post/index.php(9): CBaseController->widget('zii.widgets.CLi...', Array)
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CBaseController.php(126): require('/Applications/X...')
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CBaseController.php(95): CBaseController->renderInternal('/Applications/X...', Array, true)
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(869): CBaseController->renderFile('/Applications/X...', Array, true)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(782): CController->renderPartial('index', Array, true)
#10 /Applications/XAMPP/xamppfiles/htdocs/blog/protected/controllers/PostController.php(136): CController->render('index', Array)
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): PostController->actionIndex()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#13 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#14 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilter.php(40): CFilterChain->run()
#15 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#16 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#17 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#18 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(291): CFilterChain->run()
#19 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#20 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('')
#21 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('')
#22 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#23 /Applications/XAMPP/xamppfiles/htdocs/blog/index.php(11): CApplication->run()
#24 {main}
REQUEST_URI=/blog/
---
2016/09/08 15:46:08 [error] [exception.CException] exception 'CException' with message 'CAssetManager.basePath "/Applications/XAMPP/xamppfiles/htdocs/blog/assets" is invalid. Please make sure the directory exists and is writable by the Web server process.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CAssetManager.php:138
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CAssetManager.php(123): CAssetManager->setBasePath('/Applications/X...')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CAssetManager.php(217): CAssetManager->getBasePath()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/zii/widgets/CListView.php(217): CAssetManager->publish('/Applications/X...')
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CBaseController.php(147): CListView->init()
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CBaseController.php(180): CBaseController->createWidget('zii.widgets.CLi...', Array)
#5 /Applications/XAMPP/xamppfiles/htdocs/blog/protected/views/post/index.php(9): CBaseController->widget('zii.widgets.CLi...', Array)
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CBaseController.php(126): require('/Applications/X...')
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CBaseController.php(95): CBaseController->renderInternal('/Applications/X...', Array, true)
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(869): CBaseController->renderFile('/Applications/X...', Array, true)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(782): CController->renderPartial('index', Array, true)
#10 /Applications/XAMPP/xamppfiles/htdocs/blog/protected/controllers/PostController.php(136): CController->render('index', Array)
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): PostController->actionIndex()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#13 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#14 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilter.php(40): CFilterChain->run()
#15 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#16 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#17 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#18 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(291): CFilterChain->run()
#19 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#20 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('')
#21 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('')
#22 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#23 /Applications/XAMPP/xamppfiles/htdocs/blog/index.php(11): CApplication->run()
#24 {main}
REQUEST_URI=/blog/
---
2016/09/08 16:05:28 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:08:48 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:09:12 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:11:27 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:11:29 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:11:29 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:12:14 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:12:15 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:12:15 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:12:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:12:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:12:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:12:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:12:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:13:50 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:14:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:14:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:14:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:14:31 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:14:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:14:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:14:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:17:17 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:17:18 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:17:18 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:17:18 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:17:18 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:17:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:17:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:17:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:17:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:17:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:17:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:17:29 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:17:31 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:17:31 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:17:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:18:29 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii/default/login".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/default/log...')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii/default/login
---
2016/09/08 16:26:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii/default/login".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/default/log...')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii/default/login
---
2016/09/08 16:33:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:40:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:40:17 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:40:18 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:42:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:42:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:42:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:42:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:42:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:42:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:42:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:42:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:42:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:42:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:42:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:42:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 17:08:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "1".' in C:\xampp\htdocs\YII\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CController.php(270): CController->missingAction('1')
#1 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): CController->run('1')
#2 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('post/1')
#3 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#5 {main}
REQUEST_URI=/blog/post/1
---
2016/09/08 17:08:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "2".' in C:\xampp\htdocs\YII\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CController.php(270): CController->missingAction('2')
#1 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): CController->run('2')
#2 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('post/2')
#3 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#5 {main}
REQUEST_URI=/blog/post/2
---
2016/09/08 17:09:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "1".' in C:\xampp\htdocs\YII\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CController.php(270): CController->missingAction('1')
#1 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): CController->run('1')
#2 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('post/1')
#3 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#5 {main}
REQUEST_URI=/blog/post/1
---
2016/09/08 17:11:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "css/main.css".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('css/main.css')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#3 {main}
REQUEST_URI=/blog/css/main.css
HTTP_REFERER=http://localhost/blog/
---
2016/09/08 17:11:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "assets/69941337/highlight.css".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('assets/69941337...')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#3 {main}
REQUEST_URI=/blog/assets/69941337/highlight.css
HTTP_REFERER=http://localhost/blog/
---
2016/09/08 17:11:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "css/form.css".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('css/form.css')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#3 {main}
REQUEST_URI=/blog/css/form.css
HTTP_REFERER=http://localhost/blog/
---
2016/09/08 17:11:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "css/screen.css".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('css/screen.css')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#3 {main}
REQUEST_URI=/blog/css/screen.css
HTTP_REFERER=http://localhost/blog/
---
2016/09/08 17:11:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "assets/f00badb6/listview/styles.css".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('assets/f00badb6...')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#3 {main}
REQUEST_URI=/blog/assets/f00badb6/listview/styles.css
HTTP_REFERER=http://localhost/blog/
---
2016/09/08 17:11:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "assets/77306bbf/pager.css".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('assets/77306bbf...')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#3 {main}
REQUEST_URI=/blog/assets/77306bbf/pager.css
HTTP_REFERER=http://localhost/blog/
---
2016/09/08 17:11:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "assets/6f275b19/jquery.js".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('assets/6f275b19...')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#3 {main}
REQUEST_URI=/blog/assets/6f275b19/jquery.js
HTTP_REFERER=http://localhost/blog/
---
2016/09/08 17:11:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "assets/6f275b19/jquery.ba-bbq.js".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('assets/6f275b19...')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#3 {main}
REQUEST_URI=/blog/assets/6f275b19/jquery.ba-bbq.js
HTTP_REFERER=http://localhost/blog/
---
2016/09/08 17:11:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "assets/f00badb6/listview/jquery.yiilistview.js".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('assets/f00badb6...')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#3 {main}
REQUEST_URI=/blog/assets/f00badb6/listview/jquery.yiilistview.js
HTTP_REFERER=http://localhost/blog/
---
2016/09/08 17:11:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "css/print.css".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('css/print.css')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#3 {main}
REQUEST_URI=/blog/css/print.css
HTTP_REFERER=http://localhost/blog/
---
2016/09/08 17:11:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "assets/f00badb6/listview/styles.css".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('assets/f00badb6...')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#3 {main}
REQUEST_URI=/blog/assets/f00badb6/listview/styles.css
HTTP_REFERER=http://localhost/blog/
---
2016/09/08 17:11:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "css/main.css".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('css/main.css')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#3 {main}
REQUEST_URI=/blog/css/main.css
HTTP_REFERER=http://localhost/blog/
---
2016/09/08 17:11:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "css/screen.css".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('css/screen.css')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#3 {main}
REQUEST_URI=/blog/css/screen.css
HTTP_REFERER=http://localhost/blog/
---
2016/09/08 17:11:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "assets/77306bbf/pager.css".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('assets/77306bbf...')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#3 {main}
REQUEST_URI=/blog/assets/77306bbf/pager.css
HTTP_REFERER=http://localhost/blog/
---
2016/09/08 17:11:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "css/form.css".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('css/form.css')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#3 {main}
REQUEST_URI=/blog/css/form.css
HTTP_REFERER=http://localhost/blog/
---
2016/09/08 17:11:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "assets/69941337/highlight.css".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('assets/69941337...')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#3 {main}
REQUEST_URI=/blog/assets/69941337/highlight.css
HTTP_REFERER=http://localhost/blog/
---
2016/09/08 17:11:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "assets/6f275b19/jquery.js".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('assets/6f275b19...')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#3 {main}
REQUEST_URI=/blog/assets/6f275b19/jquery.js
HTTP_REFERER=http://localhost/blog/
---
2016/09/08 17:11:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "assets/f00badb6/listview/jquery.yiilistview.js".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('assets/f00badb6...')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#3 {main}
REQUEST_URI=/blog/assets/f00badb6/listview/jquery.yiilistview.js
HTTP_REFERER=http://localhost/blog/
---
2016/09/08 17:11:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "assets/6f275b19/jquery.ba-bbq.js".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('assets/6f275b19...')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#3 {main}
REQUEST_URI=/blog/assets/6f275b19/jquery.ba-bbq.js
HTTP_REFERER=http://localhost/blog/
---
2016/09/08 17:11:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "css/print.css".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('css/print.css')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#3 {main}
REQUEST_URI=/blog/css/print.css
HTTP_REFERER=http://localhost/blog/
---
2016/09/08 17:11:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "assets/f00badb6/listview/jquery.yiilistview.js".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('assets/f00badb6...')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#3 {main}
REQUEST_URI=/blog/assets/f00badb6/listview/jquery.yiilistview.js
HTTP_REFERER=http://localhost/blog/
---
2016/09/09 12:41:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user/lista".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('user/lista')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#3 {main}
REQUEST_URI=/blog/user/lista
HTTP_REFERER=http://localhost/blog/
---
2016/09/09 12:43:50 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user/lista".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('user/lista')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#3 {main}
REQUEST_URI=/blog/user/lista
HTTP_REFERER=http://localhost/blog/
---
2016/09/09 12:43:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user/lista".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('user/lista')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#3 {main}
REQUEST_URI=/blog/user/lista
HTTP_REFERER=http://localhost/blog/
---
2016/09/09 12:44:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user/lista".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('user/lista')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#3 {main}
REQUEST_URI=/blog/user/lista
HTTP_REFERER=http://localhost/blog/
---
2016/09/09 12:44:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user/lista".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('user/lista')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#3 {main}
REQUEST_URI=/blog/user/lista
HTTP_REFERER=http://localhost/blog/
---
2016/09/09 12:46:07 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user/lista".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('user/lista')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#3 {main}
REQUEST_URI=/blog/user/lista
HTTP_REFERER=http://localhost/blog/
---
2016/09/09 12:46:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user/lista".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('user/lista')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#3 {main}
REQUEST_URI=/blog/user/lista
HTTP_REFERER=http://localhost/blog/
---
2016/09/09 12:46:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user/lista".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('user/lista')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#3 {main}
REQUEST_URI=/blog/user/lista
HTTP_REFERER=http://localhost/blog/
---
2016/09/09 12:46:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user/lista".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('user/lista')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#3 {main}
REQUEST_URI=/blog/user/lista
HTTP_REFERER=http://localhost/blog/
---
2016/09/09 12:46:10 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user/lista".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('user/lista')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#3 {main}
REQUEST_URI=/blog/user/lista
HTTP_REFERER=http://localhost/blog/
---
2016/09/09 12:46:10 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user/lista".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('user/lista')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#3 {main}
REQUEST_URI=/blog/user/lista
HTTP_REFERER=http://localhost/blog/
---
2016/09/09 12:46:10 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user/lista".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('user/lista')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#3 {main}
REQUEST_URI=/blog/user/lista
HTTP_REFERER=http://localhost/blog/
---
2016/09/09 12:56:26 [error] [exception.CException] exception 'CException' with message 'The property "itemView" cannot be empty.' in C:\xampp\htdocs\YII\framework\zii\widgets\CListView.php:210
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CBaseController.php(147): CListView->init()
#1 C:\xampp\htdocs\YII\framework\web\CBaseController.php(180): CBaseController->createWidget('zii.widgets.CLi...', Array)
#2 C:\xampp\htdocs\blog\protected\views\user\listaUtenti.php(6): CBaseController->widget('zii.widgets.CLi...', Array)
#3 C:\xampp\htdocs\YII\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\YII\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#5 C:\xampp\htdocs\YII\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#6 C:\xampp\htdocs\YII\framework\web\CController.php(782): CController->renderPartial('listaUtenti', Array, true)
#7 C:\xampp\htdocs\blog\protected\controllers\UserController.php(35): CController->render('listaUtenti', Array)
#8 C:\xampp\htdocs\YII\framework\web\actions\CInlineAction.php(49): UserController->actionLista()
#9 C:\xampp\htdocs\YII\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\YII\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\YII\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): CController->run('lista')
#13 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('user/lista')
#14 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#16 {main}
REQUEST_URI=/blog/user/lista
HTTP_REFERER=http://localhost/blog/
---
2016/09/09 13:03:51 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'blog.tbl_postazzo' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `tbl_postazzo`.
in C:\xampp\htdocs\blog\protected\models\Comment.php (129)
in C:\xampp\htdocs\blog\protected\components\RecentComments.php (12)
in C:\xampp\htdocs\blog\protected\components\views\recentComments.php (2)
2016/09/09 13:03:51 [error] [exception.CDbException] exception 'CDbException' with message 'The table "{{postazzo}}" for active record class "Post" cannot be found in the database.' in C:\xampp\htdocs\YII\framework\db\ar\CActiveRecord.php:2387
Stack trace:
#0 C:\xampp\htdocs\YII\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Post))
#1 C:\xampp\htdocs\YII\framework\db\ar\CActiveRecord.php(661): CActiveRecord->getMetaData()
#2 C:\xampp\htdocs\YII\framework\db\ar\CActiveFinder.php(386): CActiveRecord->getTableSchema()
#3 C:\xampp\htdocs\YII\framework\db\ar\CActiveFinder.php(281): CJoinElement->__construct(Object(CActiveFinder), Object(CBelongsToRelation), Object(CJoinElement), 1)
#4 C:\xampp\htdocs\YII\framework\db\ar\CActiveFinder.php(299): CActiveFinder->buildJoinTree(Object(CJoinElement), 'post')
#5 C:\xampp\htdocs\YII\framework\db\ar\CActiveFinder.php(48): CActiveFinder->buildJoinTree(Object(CJoinElement), Array)
#6 C:\xampp\htdocs\YII\framework\db\ar\CActiveRecord.php(912): CActiveFinder->__construct(Object(Comment), Array)
#7 C:\xampp\htdocs\YII\framework\db\ar\CActiveRecord.php(1360): CActiveRecord->getActiveFinder(Array)
#8 C:\xampp\htdocs\YII\framework\db\ar\CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#9 C:\xampp\htdocs\blog\protected\models\Comment.php(129): CActiveRecord->findAll(Array)
#10 C:\xampp\htdocs\blog\protected\components\RecentComments.php(12): Comment->findRecentComments(10)
#11 C:\xampp\htdocs\blog\protected\components\views\recentComments.php(2): RecentComments->getRecentComments()
#12 C:\xampp\htdocs\YII\framework\web\CBaseController.php(130): require('C:\\xampp\\htdocs...')
#13 C:\xampp\htdocs\YII\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', NULL, false)
#14 C:\xampp\htdocs\YII\framework\web\widgets\CWidget.php(244): CBaseController->renderFile('C:\\xampp\\htdocs...', NULL, false)
#15 C:\xampp\htdocs\blog\protected\components\RecentComments.php(17): CWidget->render('recentComments')
#16 C:\xampp\htdocs\YII\framework\zii\widgets\CPortlet.php(97): RecentComments->renderContent()
#17 C:\xampp\htdocs\YII\framework\web\CBaseController.php(181): CPortlet->run()
#18 C:\xampp\htdocs\blog\protected\views\layouts\column2.php(18): CBaseController->widget('RecentComments', Array)
#19 C:\xampp\htdocs\YII\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#20 C:\xampp\htdocs\YII\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#21 C:\xampp\htdocs\YII\framework\web\CController.php(784): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#22 C:\xampp\htdocs\blog\protected\controllers\UserController.php(35): CController->render('listaUtenti', Array)
#23 C:\xampp\htdocs\YII\framework\web\actions\CInlineAction.php(49): UserController->actionLista()
#24 C:\xampp\htdocs\YII\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#25 C:\xampp\htdocs\YII\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#26 C:\xampp\htdocs\YII\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#27 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): CController->run('lista')
#28 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('user/lista')
#29 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#30 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#31 {main}
REQUEST_URI=/blog/user/lista
HTTP_REFERER=http://localhost/blog/
---
2016/09/09 13:06:25 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'blog.tbl_users' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `tbl_users`.
in C:\xampp\htdocs\blog\protected\views\post\_view.php (6)
in C:\xampp\htdocs\blog\protected\views\post\index.php (9)
in C:\xampp\htdocs\blog\protected\controllers\PostController.php (136)
2016/09/09 13:06:25 [error] [exception.CDbException] exception 'CDbException' with message 'The table "{{users}}" for active record class "User" cannot be found in the database.' in C:\xampp\htdocs\YII\framework\db\ar\CActiveRecord.php:2387
Stack trace:
#0 C:\xampp\htdocs\YII\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(User))
#1 C:\xampp\htdocs\YII\framework\db\ar\CActiveRecord.php(661): CActiveRecord->getMetaData()
#2 C:\xampp\htdocs\YII\framework\db\ar\CActiveFinder.php(386): CActiveRecord->getTableSchema()
#3 C:\xampp\htdocs\YII\framework\db\ar\CActiveFinder.php(281): CJoinElement->__construct(Object(CActiveFinder), Object(CBelongsToRelation), Object(CJoinElement), 1)
#4 C:\xampp\htdocs\YII\framework\db\ar\CActiveFinder.php(48): CActiveFinder->buildJoinTree(Object(CJoinElement), 'author')
#5 C:\xampp\htdocs\YII\framework\db\ar\CActiveRecord.php(912): CActiveFinder->__construct(Object(Post), 'author')
#6 C:\xampp\htdocs\YII\framework\db\ar\CActiveRecord.php(280): CActiveRecord->getActiveFinder('author')
#7 C:\xampp\htdocs\YII\framework\db\ar\CActiveRecord.php(143): CActiveRecord->getRelated('author')
#8 C:\xampp\htdocs\blog\protected\views\post\_view.php(6): CActiveRecord->__get('author')
#9 C:\xampp\htdocs\YII\framework\web\CBaseController.php(130): require('C:\\xampp\\htdocs...')
#10 C:\xampp\htdocs\YII\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, false)
#11 C:\xampp\htdocs\YII\framework\zii\widgets\CListView.php(291): CBaseController->renderFile('C:\\xampp\\htdocs...', Array)
#12 C:\xampp\htdocs\YII\framework\zii\widgets\CBaseListView.php(181): CListView->renderItems()
#13 [internal function]: CBaseListView->renderSection(Array)
#14 C:\xampp\htdocs\YII\framework\zii\widgets\CBaseListView.php(164): preg_replace_callback('/{(\\w+)}/', Array, '{items}\n{pager}')
#15 C:\xampp\htdocs\YII\framework\zii\widgets\CBaseListView.php(149): CBaseListView->renderContent()
#16 C:\xampp\htdocs\YII\framework\web\CBaseController.php(181): CBaseListView->run()
#17 C:\xampp\htdocs\blog\protected\views\post\index.php(9): CBaseController->widget('zii.widgets.CLi...', Array)
#18 C:\xampp\htdocs\YII\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#19 C:\xampp\htdocs\YII\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#20 C:\xampp\htdocs\YII\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#21 C:\xampp\htdocs\YII\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#22 C:\xampp\htdocs\blog\protected\controllers\PostController.php(136): CController->render('index', Array)
#23 C:\xampp\htdocs\YII\framework\web\actions\CInlineAction.php(49): PostController->actionIndex()
#24 C:\xampp\htdocs\YII\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#25 C:\xampp\htdocs\YII\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#26 C:\xampp\htdocs\YII\framework\web\filters\CFilter.php(40): CFilterChain->run()
#27 C:\xampp\htdocs\YII\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#28 C:\xampp\htdocs\YII\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#29 C:\xampp\htdocs\YII\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#30 C:\xampp\htdocs\YII\framework\web\CController.php(291): CFilterChain->run()
#31 C:\xampp\htdocs\YII\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#32 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): CController->run('index')
#33 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('post/index')
#34 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#35 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#36 {main}
REQUEST_URI=/blog/post/index
HTTP_REFERER=http://localhost/blog/user/lista
---
2016/09/09 15:01:34 [error] [exception.CException] exception 'CException' with message 'Property "User.url" is not defined.' in C:\xampp\htdocs\YII\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\YII\framework\db\ar\CActiveRecord.php(145): CComponent->__get('url')
#1 C:\xampp\htdocs\blog\protected\views\user\_utente.php(5): CActiveRecord->__get('url')
#2 C:\xampp\htdocs\YII\framework\web\CBaseController.php(130): require('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\YII\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, false)
#4 C:\xampp\htdocs\YII\framework\zii\widgets\CListView.php(291): CBaseController->renderFile('C:\\xampp\\htdocs...', Array)
#5 C:\xampp\htdocs\YII\framework\zii\widgets\CBaseListView.php(181): CListView->renderItems()
#6 [internal function]: CBaseListView->renderSection(Array)
#7 C:\xampp\htdocs\YII\framework\zii\widgets\CBaseListView.php(164): preg_replace_callback('/{(\\w+)}/', Array, '{summary}\n{sort...')
#8 C:\xampp\htdocs\YII\framework\zii\widgets\CBaseListView.php(149): CBaseListView->renderContent()
#9 C:\xampp\htdocs\YII\framework\web\CBaseController.php(181): CBaseListView->run()
#10 C:\xampp\htdocs\blog\protected\views\user\listaUtenti.php(14): CBaseController->widget('zii.widgets.CLi...', Array)
#11 C:\xampp\htdocs\YII\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#12 C:\xampp\htdocs\YII\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#13 C:\xampp\htdocs\YII\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#14 C:\xampp\htdocs\YII\framework\web\CController.php(782): CController->renderPartial('listaUtenti', Array, true)
#15 C:\xampp\htdocs\blog\protected\controllers\UserController.php(35): CController->render('listaUtenti', Array)
#16 C:\xampp\htdocs\YII\framework\web\actions\CInlineAction.php(49): UserController->actionLista()
#17 C:\xampp\htdocs\YII\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#18 C:\xampp\htdocs\YII\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#19 C:\xampp\htdocs\YII\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#20 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): CController->run('lista')
#21 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('user/lista')
#22 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#23 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#24 {main}
REQUEST_URI=/blog/user/lista
HTTP_REFERER=http://localhost/blog/site/page?view=about
---
2016/09/09 15:06:48 [error] [exception.CException] exception 'CException' with message 'Property "User.url" is not defined.' in C:\xampp\htdocs\YII\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\YII\framework\db\ar\CActiveRecord.php(145): CComponent->__get('url')
#1 C:\xampp\htdocs\blog\protected\views\user\_utente.php(4): CActiveRecord->__get('url')
#2 C:\xampp\htdocs\YII\framework\web\CBaseController.php(130): require('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\YII\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, false)
#4 C:\xampp\htdocs\YII\framework\zii\widgets\CListView.php(291): CBaseController->renderFile('C:\\xampp\\htdocs...', Array)
#5 C:\xampp\htdocs\YII\framework\zii\widgets\CBaseListView.php(181): CListView->renderItems()
#6 [internal function]: CBaseListView->renderSection(Array)
#7 C:\xampp\htdocs\YII\framework\zii\widgets\CBaseListView.php(164): preg_replace_callback('/{(\\w+)}/', Array, '{summary}\n{sort...')
#8 C:\xampp\htdocs\YII\framework\zii\widgets\CBaseListView.php(149): CBaseListView->renderContent()
#9 C:\xampp\htdocs\YII\framework\web\CBaseController.php(181): CBaseListView->run()
#10 C:\xampp\htdocs\blog\protected\views\user\listaUtenti.php(14): CBaseController->widget('zii.widgets.CLi...', Array)
#11 C:\xampp\htdocs\YII\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#12 C:\xampp\htdocs\YII\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#13 C:\xampp\htdocs\YII\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#14 C:\xampp\htdocs\YII\framework\web\CController.php(782): CController->renderPartial('listaUtenti', Array, true)
#15 C:\xampp\htdocs\blog\protected\controllers\UserController.php(35): CController->render('listaUtenti', Array)
#16 C:\xampp\htdocs\YII\framework\web\actions\CInlineAction.php(49): UserController->actionLista()
#17 C:\xampp\htdocs\YII\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#18 C:\xampp\htdocs\YII\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#19 C:\xampp\htdocs\YII\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#20 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): CController->run('lista')
#21 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('user/lista')
#22 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#23 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#24 {main}
REQUEST_URI=/blog/user/lista
HTTP_REFERER=http://localhost/blog/post/index
---
2016/09/09 15:10:53 [error] [exception.CException] exception 'CException' with message 'Property "User.title" is not defined.' in C:\xampp\htdocs\YII\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\YII\framework\db\ar\CActiveRecord.php(145): CComponent->__get('title')
#1 C:\xampp\htdocs\blog\protected\views\user\_utente.php(4): CActiveRecord->__get('title')
#2 C:\xampp\htdocs\YII\framework\web\CBaseController.php(130): require('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\YII\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, false)
#4 C:\xampp\htdocs\YII\framework\zii\widgets\CListView.php(291): CBaseController->renderFile('C:\\xampp\\htdocs...', Array)
#5 C:\xampp\htdocs\YII\framework\zii\widgets\CBaseListView.php(181): CListView->renderItems()
#6 [internal function]: CBaseListView->renderSection(Array)
#7 C:\xampp\htdocs\YII\framework\zii\widgets\CBaseListView.php(164): preg_replace_callback('/{(\\w+)}/', Array, '{summary}\n{sort...')
#8 C:\xampp\htdocs\YII\framework\zii\widgets\CBaseListView.php(149): CBaseListView->renderContent()
#9 C:\xampp\htdocs\YII\framework\web\CBaseController.php(181): CBaseListView->run()
#10 C:\xampp\htdocs\blog\protected\views\user\listaUtenti.php(14): CBaseController->widget('zii.widgets.CLi...', Array)
#11 C:\xampp\htdocs\YII\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#12 C:\xampp\htdocs\YII\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#13 C:\xampp\htdocs\YII\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#14 C:\xampp\htdocs\YII\framework\web\CController.php(782): CController->renderPartial('listaUtenti', Array, true)
#15 C:\xampp\htdocs\blog\protected\controllers\UserController.php(35): CController->render('listaUtenti', Array)
#16 C:\xampp\htdocs\YII\framework\web\actions\CInlineAction.php(49): UserController->actionLista()
#17 C:\xampp\htdocs\YII\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#18 C:\xampp\htdocs\YII\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#19 C:\xampp\htdocs\YII\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#20 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): CController->run('lista')
#21 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('user/lista')
#22 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#23 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#24 {main}
REQUEST_URI=/blog/user/lista
HTTP_REFERER=http://localhost/blog/post/index
---
2016/09/09 15:11:00 [error] [exception.CException] exception 'CException' with message 'Property "User.title" is not defined.' in C:\xampp\htdocs\YII\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\YII\framework\db\ar\CActiveRecord.php(145): CComponent->__get('title')
#1 C:\xampp\htdocs\blog\protected\views\user\_utente.php(4): CActiveRecord->__get('title')
#2 C:\xampp\htdocs\YII\framework\web\CBaseController.php(130): require('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\YII\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, false)
#4 C:\xampp\htdocs\YII\framework\zii\widgets\CListView.php(291): CBaseController->renderFile('C:\\xampp\\htdocs...', Array)
#5 C:\xampp\htdocs\YII\framework\zii\widgets\CBaseListView.php(181): CListView->renderItems()
#6 [internal function]: CBaseListView->renderSection(Array)
#7 C:\xampp\htdocs\YII\framework\zii\widgets\CBaseListView.php(164): preg_replace_callback('/{(\\w+)}/', Array, '{summary}\n{sort...')
#8 C:\xampp\htdocs\YII\framework\zii\widgets\CBaseListView.php(149): CBaseListView->renderContent()
#9 C:\xampp\htdocs\YII\framework\web\CBaseController.php(181): CBaseListView->run()
#10 C:\xampp\htdocs\blog\protected\views\user\listaUtenti.php(14): CBaseController->widget('zii.widgets.CLi...', Array)
#11 C:\xampp\htdocs\YII\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#12 C:\xampp\htdocs\YII\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#13 C:\xampp\htdocs\YII\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#14 C:\xampp\htdocs\YII\framework\web\CController.php(782): CController->renderPartial('listaUtenti', Array, true)
#15 C:\xampp\htdocs\blog\protected\controllers\UserController.php(35): CController->render('listaUtenti', Array)
#16 C:\xampp\htdocs\YII\framework\web\actions\CInlineAction.php(49): UserController->actionLista()
#17 C:\xampp\htdocs\YII\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#18 C:\xampp\htdocs\YII\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#19 C:\xampp\htdocs\YII\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#20 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): CController->run('lista')
#21 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('user/lista')
#22 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#23 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#24 {main}
REQUEST_URI=/blog/user/lista
HTTP_REFERER=http://localhost/blog/site/contact
---
2016/09/09 15:20:20 [error] [exception.CException] exception 'CException' with message 'Property "Post.url" is not defined.' in C:\xampp\htdocs\YII\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\YII\framework\db\ar\CActiveRecord.php(145): CComponent->__get('url')
#1 C:\xampp\htdocs\blog\protected\views\post\_view.php(3): CActiveRecord->__get('url')
#2 C:\xampp\htdocs\YII\framework\web\CBaseController.php(130): require('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\YII\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, false)
#4 C:\xampp\htdocs\YII\framework\zii\widgets\CListView.php(291): CBaseController->renderFile('C:\\xampp\\htdocs...', Array)
#5 C:\xampp\htdocs\YII\framework\zii\widgets\CBaseListView.php(181): CListView->renderItems()
#6 [internal function]: CBaseListView->renderSection(Array)
#7 C:\xampp\htdocs\YII\framework\zii\widgets\CBaseListView.php(164): preg_replace_callback('/{(\\w+)}/', Array, '{items}\n{pager}')
#8 C:\xampp\htdocs\YII\framework\zii\widgets\CBaseListView.php(149): CBaseListView->renderContent()
#9 C:\xampp\htdocs\YII\framework\web\CBaseController.php(181): CBaseListView->run()
#10 C:\xampp\htdocs\blog\protected\views\post\index.php(9): CBaseController->widget('zii.widgets.CLi...', Array)
#11 C:\xampp\htdocs\YII\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#12 C:\xampp\htdocs\YII\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#13 C:\xampp\htdocs\YII\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#14 C:\xampp\htdocs\YII\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#15 C:\xampp\htdocs\blog\protected\controllers\PostController.php(136): CController->render('index', Array)
#16 C:\xampp\htdocs\YII\framework\web\actions\CInlineAction.php(49): PostController->actionIndex()
#17 C:\xampp\htdocs\YII\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#18 C:\xampp\htdocs\YII\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#19 C:\xampp\htdocs\YII\framework\web\filters\CFilter.php(40): CFilterChain->run()
#20 C:\xampp\htdocs\YII\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#21 C:\xampp\htdocs\YII\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#22 C:\xampp\htdocs\YII\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#23 C:\xampp\htdocs\YII\framework\web\CController.php(291): CFilterChain->run()
#24 C:\xampp\htdocs\YII\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#25 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): CController->run('index')
#26 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('post/index')
#27 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#28 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#29 {main}
REQUEST_URI=/blog/post/index
HTTP_REFERER=http://localhost/blog/user/lista
---
2016/09/09 15:21:47 [error] [exception.CException] exception 'CException' with message 'Property "Post.url" is not defined.' in C:\xampp\htdocs\YII\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\YII\framework\db\ar\CActiveRecord.php(145): CComponent->__get('url')
#1 C:\xampp\htdocs\blog\protected\views\post\_view.php(3): CActiveRecord->__get('url')
#2 C:\xampp\htdocs\YII\framework\web\CBaseController.php(130): require('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\YII\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, false)
#4 C:\xampp\htdocs\YII\framework\zii\widgets\CListView.php(291): CBaseController->renderFile('C:\\xampp\\htdocs...', Array)
#5 C:\xampp\htdocs\YII\framework\zii\widgets\CBaseListView.php(181): CListView->renderItems()
#6 [internal function]: CBaseListView->renderSection(Array)
#7 C:\xampp\htdocs\YII\framework\zii\widgets\CBaseListView.php(164): preg_replace_callback('/{(\\w+)}/', Array, '{items}\n{pager}')
#8 C:\xampp\htdocs\YII\framework\zii\widgets\CBaseListView.php(149): CBaseListView->renderContent()
#9 C:\xampp\htdocs\YII\framework\web\CBaseController.php(181): CBaseListView->run()
#10 C:\xampp\htdocs\blog\protected\views\post\index.php(9): CBaseController->widget('zii.widgets.CLi...', Array)
#11 C:\xampp\htdocs\YII\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#12 C:\xampp\htdocs\YII\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#13 C:\xampp\htdocs\YII\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#14 C:\xampp\htdocs\YII\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#15 C:\xampp\htdocs\blog\protected\controllers\PostController.php(136): CController->render('index', Array)
#16 C:\xampp\htdocs\YII\framework\web\actions\CInlineAction.php(49): PostController->actionIndex()
#17 C:\xampp\htdocs\YII\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#18 C:\xampp\htdocs\YII\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#19 C:\xampp\htdocs\YII\framework\web\filters\CFilter.php(40): CFilterChain->run()
#20 C:\xampp\htdocs\YII\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#21 C:\xampp\htdocs\YII\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#22 C:\xampp\htdocs\YII\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#23 C:\xampp\htdocs\YII\framework\web\CController.php(291): CFilterChain->run()
#24 C:\xampp\htdocs\YII\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#25 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): CController->run('index')
#26 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('post/index')
#27 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#28 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#29 {main}
REQUEST_URI=/blog/post/index
HTTP_REFERER=http://localhost/blog/user/lista
---
2016/09/09 15:23:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "view".' in C:\xampp\htdocs\YII\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CController.php(270): CController->missingAction('view')
#1 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): CController->run('view')
#2 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('user/view')
#3 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#5 {main}
REQUEST_URI=/blog/user/view?id=3&username=Paolo
HTTP_REFERER=http://localhost/blog/user/lista
---
2016/09/09 15:31:41 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "view".' in C:\xampp\htdocs\YII\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CController.php(270): CController->missingAction('view')
#1 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): CController->run('view')
#2 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('user/view')
#3 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#5 {main}
REQUEST_URI=/blog/user/view?id=1&username=demo
HTTP_REFERER=http://localhost/blog/user/lista
---
2016/09/09 15:31:46 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "view".' in C:\xampp\htdocs\YII\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CController.php(270): CController->missingAction('view')
#1 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): CController->run('view')
#2 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('user/view')
#3 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#5 {main}
REQUEST_URI=/blog/user/view?id=3&username=Paolo
HTTP_REFERER=http://localhost/blog/user/lista
---
2016/09/09 15:36:47 [error] [exception.CException] exception 'CException' with message 'Property "Post.url" is not defined.' in C:\xampp\htdocs\YII\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\YII\framework\db\ar\CActiveRecord.php(145): CComponent->__get('url')
#1 C:\xampp\htdocs\blog\protected\models\Comment.php(97): CActiveRecord->__get('url')
#2 C:\xampp\htdocs\blog\protected\components\views\recentComments.php(4): Comment->getUrl()
#3 C:\xampp\htdocs\YII\framework\web\CBaseController.php(130): require('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\YII\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', NULL, false)
#5 C:\xampp\htdocs\YII\framework\web\widgets\CWidget.php(244): CBaseController->renderFile('C:\\xampp\\htdocs...', NULL, false)
#6 C:\xampp\htdocs\blog\protected\components\RecentComments.php(17): CWidget->render('recentComments')
#7 C:\xampp\htdocs\YII\framework\zii\widgets\CPortlet.php(97): RecentComments->renderContent()
#8 C:\xampp\htdocs\YII\framework\web\CBaseController.php(181): CPortlet->run()
#9 C:\xampp\htdocs\blog\protected\views\layouts\column2.php(18): CBaseController->widget('RecentComments', Array)
#10 C:\xampp\htdocs\YII\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#11 C:\xampp\htdocs\YII\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#12 C:\xampp\htdocs\YII\framework\web\CController.php(784): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#13 C:\xampp\htdocs\blog\protected\controllers\UserController.php(35): CController->render('listaUtenti', Array)
#14 C:\xampp\htdocs\YII\framework\web\actions\CInlineAction.php(49): UserController->actionLista()
#15 C:\xampp\htdocs\YII\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#16 C:\xampp\htdocs\YII\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#17 C:\xampp\htdocs\YII\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): CController->run('lista')
#19 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('user/lista')
#20 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#21 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#22 {main}
REQUEST_URI=/blog/user/lista
HTTP_REFERER=http://localhost/blog/post/index
---
2016/09/09 15:53:23 [error] [php] Undefined variable: utente (C:\xampp\htdocs\blog\protected\controllers\UserController.php:44)
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CController.php(286): UserController->runAction()
#1 C:\xampp\htdocs\YII\framework\web\CController.php(265): UserController->runActionWithFilters()
#2 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): UserController->run()
#3 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\blog\index.php(12): CWebApplication->run()
REQUEST_URI=/blog/user/1/demo
in C:\xampp\htdocs\blog\protected\controllers\UserController.php (44)
in C:\xampp\htdocs\blog\index.php (12)
2016/09/09 15:57:31 [error] [exception.CException] exception 'CException' with message 'UserController cannot find the requested view "dettaglio".' in C:\xampp\htdocs\YII\framework\web\CController.php:878
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CController.php(782): CController->renderPartial('dettaglio', Array, true)
#1 C:\xampp\htdocs\blog\protected\controllers\UserController.php(45): CController->render('dettaglio', Array)
#2 C:\xampp\htdocs\YII\framework\web\actions\CInlineAction.php(49): UserController->actionDettaglio()
#3 C:\xampp\htdocs\YII\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\YII\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\YII\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): CController->run('dettaglio')
#7 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('user/dettaglio')
#8 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#9 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#10 {main}
REQUEST_URI=/blog/user/1/demo
HTTP_REFERER=http://localhost/blog/user/lista
---
2016/09/09 17:41:10 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "update".' in C:\xampp\htdocs\YII\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CController.php(270): CController->missingAction('update')
#1 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): CController->run('update')
#2 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('user/update')
#3 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#5 {main}
REQUEST_URI=/blog/user/update
HTTP_REFERER=http://localhost/blog/user/3/Paolo
---
2016/09/09 17:42:03 [error] [php] Undefined index: id (C:\xampp\htdocs\blog\protected\controllers\UserController.php:49)
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CController.php(286): UserController->runAction()
#1 C:\xampp\htdocs\YII\framework\web\CController.php(265): UserController->runActionWithFilters()
#2 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): UserController->run()
#3 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\blog\index.php(12): CWebApplication->run()
REQUEST_URI=/blog/user/update
in C:\xampp\htdocs\blog\protected\controllers\UserController.php (49)
in C:\xampp\htdocs\blog\index.php (12)
2016/09/09 17:44:34 [error] [php] Undefined index: User (C:\xampp\htdocs\blog\protected\controllers\UserController.php:46)
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CController.php(286): UserController->runAction()
#1 C:\xampp\htdocs\YII\framework\web\CController.php(265): UserController->runActionWithFilters()
#2 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): UserController->run()
#3 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\blog\index.php(12): CWebApplication->run()
REQUEST_URI=/blog/user/update
in C:\xampp\htdocs\blog\protected\controllers\UserController.php (46)
in C:\xampp\htdocs\blog\index.php (12)
2016/09/09 17:45:49 [error] [php] Undefined index: username (C:\xampp\htdocs\blog\protected\controllers\UserController.php:46)
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CController.php(286): UserController->runAction()
#1 C:\xampp\htdocs\YII\framework\web\CController.php(265): UserController->runActionWithFilters()
#2 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): UserController->run()
#3 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\blog\index.php(12): CWebApplication->run()
REQUEST_URI=/blog/user/update
in C:\xampp\htdocs\blog\protected\controllers\UserController.php (46)
in C:\xampp\htdocs\blog\index.php (12)
2016/09/09 17:46:38 [error] [php] Undefined index: username (C:\xampp\htdocs\blog\protected\controllers\UserController.php:46)
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CController.php(286): UserController->runAction()
#1 C:\xampp\htdocs\YII\framework\web\CController.php(265): UserController->runActionWithFilters()
#2 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): UserController->run()
#3 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\blog\index.php(12): CWebApplication->run()
REQUEST_URI=/blog/user/update
in C:\xampp\htdocs\blog\protected\controllers\UserController.php (46)
in C:\xampp\htdocs\blog\index.php (12)
2016/09/09 17:47:33 [error] [php] Undefined variable: utente (C:\xampp\htdocs\blog\protected\controllers\UserController.php:47)
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CController.php(286): UserController->runAction()
#1 C:\xampp\htdocs\YII\framework\web\CController.php(265): UserController->runActionWithFilters()
#2 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): UserController->run()
#3 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\blog\index.php(12): CWebApplication->run()
REQUEST_URI=/blog/user/update
in C:\xampp\htdocs\blog\protected\controllers\UserController.php (47)
in C:\xampp\htdocs\blog\index.php (12)
2016/09/09 17:48:43 [error] [php] Undefined index: id (C:\xampp\htdocs\blog\protected\controllers\UserController.php:45)
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CController.php(286): UserController->runAction()
#1 C:\xampp\htdocs\YII\framework\web\CController.php(265): UserController->runActionWithFilters()
#2 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): UserController->run()
#3 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\blog\index.php(12): CWebApplication->run()
REQUEST_URI=/blog/user/update
in C:\xampp\htdocs\blog\protected\controllers\UserController.php (45)
in C:\xampp\htdocs\blog\index.php (12)
2016/09/09 17:48:53 [error] [php] Undefined variable: test (C:\xampp\htdocs\blog\protected\views\user\dettaglio.php:21)
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CController.php(869): UserController->renderFile()
#1 C:\xampp\htdocs\YII\framework\web\CController.php(782): UserController->renderPartial()
#2 C:\xampp\htdocs\blog\protected\controllers\UserController.php(40): UserController->render()
#3 C:\xampp\htdocs\YII\framework\web\actions\CInlineAction.php(49): UserController->actionDettaglio()
#4 C:\xampp\htdocs\YII\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\YII\framework\web\CController.php(286): UserController->runAction()
#6 C:\xampp\htdocs\YII\framework\web\CController.php(265): UserController->runActionWithFilters()
#7 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): UserController->run()
#8 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\blog\index.php(12): CWebApplication->run()
REQUEST_URI=/blog/user/3/Paolo
in C:\xampp\htdocs\blog\protected\views\user\dettaglio.php (21)
in C:\xampp\htdocs\blog\protected\controllers\UserController.php (40)
in C:\xampp\htdocs\blog\index.php (12)
2016/09/09 17:49:15 [error] [php] Undefined index: id (C:\xampp\htdocs\blog\protected\controllers\UserController.php:45)
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CController.php(286): UserController->runAction()
#1 C:\xampp\htdocs\YII\framework\web\CController.php(265): UserController->runActionWithFilters()
#2 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): UserController->run()
#3 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\blog\index.php(12): CWebApplication->run()
REQUEST_URI=/blog/user/update
in C:\xampp\htdocs\blog\protected\controllers\UserController.php (45)
in C:\xampp\htdocs\blog\index.php (12)
2016/09/09 17:49:36 [error] [php] Undefined offset: 2 (C:\xampp\htdocs\blog\protected\controllers\UserController.php:45)
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CController.php(286): UserController->runAction()
#1 C:\xampp\htdocs\YII\framework\web\CController.php(265): UserController->runActionWithFilters()
#2 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): UserController->run()
#3 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\blog\index.php(12): CWebApplication->run()
REQUEST_URI=/blog/user/update
in C:\xampp\htdocs\blog\protected\controllers\UserController.php (45)
in C:\xampp\htdocs\blog\index.php (12)
2016/09/09 17:49:52 [error] [php] Undefined offset: 3 (C:\xampp\htdocs\blog\protected\controllers\UserController.php:45)
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CController.php(286): UserController->runAction()
#1 C:\xampp\htdocs\YII\framework\web\CController.php(265): UserController->runActionWithFilters()
#2 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): UserController->run()
#3 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\blog\index.php(12): CWebApplication->run()
REQUEST_URI=/blog/user/update
in C:\xampp\htdocs\blog\protected\controllers\UserController.php (45)
in C:\xampp\htdocs\blog\index.php (12)
2016/09/09 17:54:32 [error] [php] Undefined index: User (C:\xampp\htdocs\blog\protected\controllers\UserController.php:45)
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CController.php(286): UserController->runAction()
#1 C:\xampp\htdocs\YII\framework\web\CController.php(265): UserController->runActionWithFilters()
#2 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): UserController->run()
#3 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\blog\index.php(12): CWebApplication->run()
REQUEST_URI=/blog/user/update
in C:\xampp\htdocs\blog\protected\controllers\UserController.php (45)
in C:\xampp\htdocs\blog\index.php (12)
2016/09/09 17:58:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "index".' in C:\xampp\htdocs\YII\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CController.php(270): CController->missingAction('')
#1 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): CController->run('')
#2 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('user')
#3 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#5 {main}
REQUEST_URI=/blog/user/
---
2016/09/09 17:59:06 [error] [php] Undefined variable: test (C:\xampp\htdocs\blog\protected\controllers\UserController.php:45)
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CController.php(286): UserController->runAction()
#1 C:\xampp\htdocs\YII\framework\web\CController.php(265): UserController->runActionWithFilters()
#2 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): UserController->run()
#3 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\blog\index.php(12): CWebApplication->run()
REQUEST_URI=/blog/user/3/Paolo
in C:\xampp\htdocs\blog\protected\controllers\UserController.php (45)
in C:\xampp\htdocs\blog\index.php (12)
2016/09/09 17:59:20 [error] [php] Undefined variable: test (C:\xampp\htdocs\blog\protected\views\user\dettaglio.php:21)
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CController.php(869): UserController->renderFile()
#1 C:\xampp\htdocs\YII\framework\web\CController.php(782): UserController->renderPartial()
#2 C:\xampp\htdocs\blog\protected\controllers\UserController.php(45): UserController->render()
#3 C:\xampp\htdocs\YII\framework\web\actions\CInlineAction.php(49): UserController->actionDettaglio()
#4 C:\xampp\htdocs\YII\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\YII\framework\web\CController.php(286): UserController->runAction()
#6 C:\xampp\htdocs\YII\framework\web\CController.php(265): UserController->runActionWithFilters()
#7 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): UserController->run()
#8 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\blog\index.php(12): CWebApplication->run()
REQUEST_URI=/blog/user/3/Paolo
in C:\xampp\htdocs\blog\protected\views\user\dettaglio.php (21)
in C:\xampp\htdocs\blog\protected\controllers\UserController.php (45)
in C:\xampp\htdocs\blog\index.php (12)
2016/09/09 17:59:22 [error] [php] Undefined variable: test (C:\xampp\htdocs\blog\protected\views\user\dettaglio.php:21)
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CController.php(869): UserController->renderFile()
#1 C:\xampp\htdocs\YII\framework\web\CController.php(782): UserController->renderPartial()
#2 C:\xampp\htdocs\blog\protected\controllers\UserController.php(45): UserController->render()
#3 C:\xampp\htdocs\YII\framework\web\actions\CInlineAction.php(49): UserController->actionDettaglio()
#4 C:\xampp\htdocs\YII\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\YII\framework\web\CController.php(286): UserController->runAction()
#6 C:\xampp\htdocs\YII\framework\web\CController.php(265): UserController->runActionWithFilters()
#7 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): UserController->run()
#8 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\blog\index.php(12): CWebApplication->run()
REQUEST_URI=/blog/user/3/Paolo
in C:\xampp\htdocs\blog\protected\views\user\dettaglio.php (21)
in C:\xampp\htdocs\blog\protected\controllers\UserController.php (45)
in C:\xampp\htdocs\blog\index.php (12)
2016/09/09 17:59:24 [error] [php] Undefined variable: test (C:\xampp\htdocs\blog\protected\views\user\dettaglio.php:21)
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CController.php(869): UserController->renderFile()
#1 C:\xampp\htdocs\YII\framework\web\CController.php(782): UserController->renderPartial()
#2 C:\xampp\htdocs\blog\protected\controllers\UserController.php(45): UserController->render()
#3 C:\xampp\htdocs\YII\framework\web\actions\CInlineAction.php(49): UserController->actionDettaglio()
#4 C:\xampp\htdocs\YII\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\YII\framework\web\CController.php(286): UserController->runAction()
#6 C:\xampp\htdocs\YII\framework\web\CController.php(265): UserController->runActionWithFilters()
#7 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): UserController->run()
#8 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\blog\index.php(12): CWebApplication->run()
REQUEST_URI=/blog/user/3/Paolo
in C:\xampp\htdocs\blog\protected\views\user\dettaglio.php (21)
in C:\xampp\htdocs\blog\protected\controllers\UserController.php (45)
in C:\xampp\htdocs\blog\index.php (12)
2016/09/09 18:03:24 [error] [php] Creating default object from empty value (C:\xampp\htdocs\blog\protected\controllers\UserController.php:42)
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CController.php(286): UserController->runAction()
#1 C:\xampp\htdocs\YII\framework\web\CController.php(265): UserController->runActionWithFilters()
#2 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): UserController->run()
#3 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\blog\index.php(12): CWebApplication->run()
REQUEST_URI=/blog/user/dettaglio
in C:\xampp\htdocs\blog\protected\controllers\UserController.php (42)
in C:\xampp\htdocs\blog\index.php (12)
2016/09/09 18:04:43 [error] [php] Creating default object from empty value (C:\xampp\htdocs\blog\protected\controllers\UserController.php:42)
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CController.php(286): UserController->runAction()
#1 C:\xampp\htdocs\YII\framework\web\CController.php(265): UserController->runActionWithFilters()
#2 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): UserController->run()
#3 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\blog\index.php(12): CWebApplication->run()
REQUEST_URI=/blog/user/dettaglio
in C:\xampp\htdocs\blog\protected\controllers\UserController.php (42)
in C:\xampp\htdocs\blog\index.php (12)
2016/09/09 18:05:44 [error] [php] Undefined index: Users (C:\xampp\htdocs\blog\protected\controllers\UserController.php:42)
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CController.php(286): UserController->runAction()
#1 C:\xampp\htdocs\YII\framework\web\CController.php(265): UserController->runActionWithFilters()
#2 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): UserController->run()
#3 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\blog\index.php(12): CWebApplication->run()
REQUEST_URI=/blog/user/dettaglio
in C:\xampp\htdocs\blog\protected\controllers\UserController.php (42)
in C:\xampp\htdocs\blog\index.php (12)
2016/09/09 18:12:41 [error] [exception.CDbException] exception 'CDbException' with message 'The active record cannot be updated because it is new.' in C:\xampp\htdocs\YII\framework\db\ar\CActiveRecord.php:1121
Stack trace:
#0 C:\xampp\htdocs\blog\protected\controllers\UserController.php(44): CActiveRecord->update()
#1 C:\xampp\htdocs\YII\framework\web\actions\CInlineAction.php(49): UserController->actionDettaglio()
#2 C:\xampp\htdocs\YII\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 C:\xampp\htdocs\YII\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 C:\xampp\htdocs\YII\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): CController->run('dettaglio')
#6 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('user/dettaglio')
#7 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#8 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#9 {main}
REQUEST_URI=/blog/user/dettaglio
HTTP_REFERER=http://localhost/blog/user/3/Paolo
---
2016/09/09 18:19:17 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in C:\xampp\htdocs\YII\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\YII\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\YII\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): CController->run('dettaglio')
#4 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('user/dettaglio')
#5 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#6 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#7 {main}
REQUEST_URI=/blog/user/dettaglio
HTTP_REFERER=http://localhost/blog/user/dettaglio
---
2016/09/09 18:19:22 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in C:\xampp\htdocs\YII\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\YII\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\YII\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): CController->run('dettaglio')
#4 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('user/dettaglio')
#5 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#6 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#7 {main}
REQUEST_URI=/blog/user/3/Paolo
HTTP_REFERER=http://localhost/blog/user/lista
---
2016/09/09 18:19:37 [error] [exception.CException] exception 'CException' with message 'Property "UserController._model" is not defined.' in C:\xampp\htdocs\YII\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\blog\protected\controllers\UserController.php(40): CComponent->__set('_model', Object(User))
#1 C:\xampp\htdocs\YII\framework\web\actions\CInlineAction.php(49): UserController->actionDettaglio()
#2 C:\xampp\htdocs\YII\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 C:\xampp\htdocs\YII\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 C:\xampp\htdocs\YII\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): CController->run('dettaglio')
#6 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('user/dettaglio')
#7 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#8 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#9 {main}
REQUEST_URI=/blog/user/3/Paolo
HTTP_REFERER=http://localhost/blog/user/lista
---
2016/09/09 18:19:41 [error] [exception.CException] exception 'CException' with message 'Property "UserController._model" is not defined.' in C:\xampp\htdocs\YII\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\blog\protected\controllers\UserController.php(40): CComponent->__set('_model', Object(User))
#1 C:\xampp\htdocs\YII\framework\web\actions\CInlineAction.php(49): UserController->actionDettaglio()
#2 C:\xampp\htdocs\YII\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 C:\xampp\htdocs\YII\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 C:\xampp\htdocs\YII\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): CController->run('dettaglio')
#6 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('user/dettaglio')
#7 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#8 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#9 {main}
REQUEST_URI=/blog/user/3/Paolo
HTTP_REFERER=http://localhost/blog/user/lista
---
2016/09/09 18:19:49 [error] [exception.CException] exception 'CException' with message 'Property "UserController._model" is not defined.' in C:\xampp\htdocs\YII\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\blog\protected\controllers\UserController.php(40): CComponent->__set('_model', Object(User))
#1 C:\xampp\htdocs\YII\framework\web\actions\CInlineAction.php(49): UserController->actionDettaglio()
#2 C:\xampp\htdocs\YII\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 C:\xampp\htdocs\YII\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 C:\xampp\htdocs\YII\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): CController->run('dettaglio')
#6 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('user/dettaglio')
#7 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#8 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#9 {main}
REQUEST_URI=/blog/user/3/Paolo
HTTP_REFERER=http://localhost/blog/user/lista
---
2016/09/09 18:20:43 [error] [php] Creating default object from empty value (C:\xampp\htdocs\blog\protected\controllers\UserController.php:45)
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CController.php(286): UserController->runAction()
#1 C:\xampp\htdocs\YII\framework\web\CController.php(265): UserController->runActionWithFilters()
#2 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): UserController->run()
#3 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\blog\index.php(12): CWebApplication->run()
REQUEST_URI=/blog/user/dettaglio
in C:\xampp\htdocs\blog\protected\controllers\UserController.php (45)
in C:\xampp\htdocs\blog\index.php (12)
2016/09/09 18:21:46 [error] [php] Creating default object from empty value (C:\xampp\htdocs\blog\protected\controllers\UserController.php:45)
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CController.php(286): UserController->runAction()
#1 C:\xampp\htdocs\YII\framework\web\CController.php(265): UserController->runActionWithFilters()
#2 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): UserController->run()
#3 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\blog\index.php(12): CWebApplication->run()
REQUEST_URI=/blog/user/dettaglio
in C:\xampp\htdocs\blog\protected\controllers\UserController.php (45)
in C:\xampp\htdocs\blog\index.php (12)
2016/09/09 18:22:20 [error] [php] Trying to get property of non-object (C:\xampp\htdocs\blog\protected\views\user\dettaglio.php:5)
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CController.php(869): UserController->renderFile()
#1 C:\xampp\htdocs\YII\framework\web\CController.php(782): UserController->renderPartial()
#2 C:\xampp\htdocs\blog\protected\controllers\UserController.php(49): UserController->render()
#3 C:\xampp\htdocs\YII\framework\web\actions\CInlineAction.php(49): UserController->actionDettaglio()
#4 C:\xampp\htdocs\YII\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\YII\framework\web\CController.php(286): UserController->runAction()
#6 C:\xampp\htdocs\YII\framework\web\CController.php(265): UserController->runActionWithFilters()
#7 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): UserController->run()
#8 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\blog\index.php(12): CWebApplication->run()
REQUEST_URI=/blog/user/dettaglio
in C:\xampp\htdocs\blog\protected\views\user\dettaglio.php (5)
in C:\xampp\htdocs\blog\protected\controllers\UserController.php (49)
in C:\xampp\htdocs\blog\index.php (12)
2016/09/09 18:22:51 [error] [php] Creating default object from empty value (C:\xampp\htdocs\blog\protected\controllers\UserController.php:45)
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CController.php(286): UserController->runAction()
#1 C:\xampp\htdocs\YII\framework\web\CController.php(265): UserController->runActionWithFilters()
#2 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): UserController->run()
#3 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\blog\index.php(12): CWebApplication->run()
REQUEST_URI=/blog/user/dettaglio
in C:\xampp\htdocs\blog\protected\controllers\UserController.php (45)
in C:\xampp\htdocs\blog\index.php (12)
2016/09/09 18:23:42 [error] [php] Creating default object from empty value (C:\xampp\htdocs\blog\protected\controllers\UserController.php:45)
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CController.php(286): UserController->runAction()
#1 C:\xampp\htdocs\YII\framework\web\CController.php(265): UserController->runActionWithFilters()
#2 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): UserController->run()
#3 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\blog\index.php(12): CWebApplication->run()
REQUEST_URI=/blog/user/dettaglio
in C:\xampp\htdocs\blog\protected\controllers\UserController.php (45)
in C:\xampp\htdocs\blog\index.php (12)
2016/09/09 18:24:46 [error] [php] Creating default object from empty value (C:\xampp\htdocs\blog\protected\controllers\UserController.php:45)
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CController.php(286): UserController->runAction()
#1 C:\xampp\htdocs\YII\framework\web\CController.php(265): UserController->runActionWithFilters()
#2 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): UserController->run()
#3 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\blog\index.php(12): CWebApplication->run()
REQUEST_URI=/blog/user/dettaglio
in C:\xampp\htdocs\blog\protected\controllers\UserController.php (45)
in C:\xampp\htdocs\blog\index.php (12)
2016/09/09 18:25:54 [error] [php] Creating default object from empty value (C:\xampp\htdocs\blog\protected\controllers\UserController.php:45)
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CController.php(286): UserController->runAction()
#1 C:\xampp\htdocs\YII\framework\web\CController.php(265): UserController->runActionWithFilters()
#2 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): UserController->run()
#3 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\blog\index.php(12): CWebApplication->run()
REQUEST_URI=/blog/user/dettaglio
in C:\xampp\htdocs\blog\protected\controllers\UserController.php (45)
in C:\xampp\htdocs\blog\index.php (12)
2016/09/09 18:26:53 [error] [php] Creating default object from empty value (C:\xampp\htdocs\blog\protected\controllers\UserController.php:45)
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CController.php(286): UserController->runAction()
#1 C:\xampp\htdocs\YII\framework\web\CController.php(265): UserController->runActionWithFilters()
#2 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): UserController->run()
#3 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\blog\index.php(12): CWebApplication->run()
REQUEST_URI=/blog/user/dettaglio
in C:\xampp\htdocs\blog\protected\controllers\UserController.php (45)
in C:\xampp\htdocs\blog\index.php (12)
2016/09/09 18:29:46 [error] [php] Undefined index: id (C:\xampp\htdocs\blog\protected\controllers\UserController.php:44)
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CController.php(286): UserController->runAction()
#1 C:\xampp\htdocs\YII\framework\web\CController.php(265): UserController->runActionWithFilters()
#2 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): UserController->run()
#3 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\blog\index.php(12): CWebApplication->run()
REQUEST_URI=/blog/user/dettaglio
in C:\xampp\htdocs\blog\protected\controllers\UserController.php (44)
in C:\xampp\htdocs\blog\index.php (12)
2016/09/09 18:29:48 [error] [php] Undefined index: id (C:\xampp\htdocs\blog\protected\controllers\UserController.php:44)
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CController.php(286): UserController->runAction()
#1 C:\xampp\htdocs\YII\framework\web\CController.php(265): UserController->runActionWithFilters()
#2 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): UserController->run()
#3 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\blog\index.php(12): CWebApplication->run()
REQUEST_URI=/blog/user/dettaglio
in C:\xampp\htdocs\blog\protected\controllers\UserController.php (44)
in C:\xampp\htdocs\blog\index.php (12)
2016/09/09 18:30:35 [error] [php] Undefined index: id (C:\xampp\htdocs\blog\protected\controllers\UserController.php:45)
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CController.php(286): UserController->runAction()
#1 C:\xampp\htdocs\YII\framework\web\CController.php(265): UserController->runActionWithFilters()
#2 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): UserController->run()
#3 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\blog\index.php(12): CWebApplication->run()
REQUEST_URI=/blog/user/dettaglio
in C:\xampp\htdocs\blog\protected\controllers\UserController.php (45)
in C:\xampp\htdocs\blog\index.php (12)
2016/09/09 18:34:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "index".' in C:\xampp\htdocs\YII\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CController.php(270): CController->missingAction('')
#1 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): CController->run('')
#2 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('user')
#3 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#5 {main}
REQUEST_URI=/blog/user/
---
2016/09/09 18:35:06 [error] [php] Creating default object from empty value (C:\xampp\htdocs\blog\protected\controllers\UserController.php:46)
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CController.php(286): UserController->runAction()
#1 C:\xampp\htdocs\YII\framework\web\CController.php(265): UserController->runActionWithFilters()
#2 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): UserController->run()
#3 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\blog\index.php(12): CWebApplication->run()
REQUEST_URI=/blog/user/dettaglio
in C:\xampp\htdocs\blog\protected\controllers\UserController.php (46)
in C:\xampp\htdocs\blog\index.php (12)
2016/09/09 18:35:39 [error] [php] Creating default object from empty value (C:\xampp\htdocs\blog\protected\controllers\UserController.php:47)
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CController.php(286): UserController->runAction()
#1 C:\xampp\htdocs\YII\framework\web\CController.php(265): UserController->runActionWithFilters()
#2 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): UserController->run()
#3 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\blog\index.php(12): CWebApplication->run()
REQUEST_URI=/blog/user/dettaglio
in C:\xampp\htdocs\blog\protected\controllers\UserController.php (47)
in C:\xampp\htdocs\blog\index.php (12)
2016/09/09 18:35:40 [error] [php] Creating default object from empty value (C:\xampp\htdocs\blog\protected\controllers\UserController.php:47)
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CController.php(286): UserController->runAction()
#1 C:\xampp\htdocs\YII\framework\web\CController.php(265): UserController->runActionWithFilters()
#2 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): UserController->run()
#3 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\blog\index.php(12): CWebApplication->run()
REQUEST_URI=/blog/user/dettaglio
in C:\xampp\htdocs\blog\protected\controllers\UserController.php (47)
in C:\xampp\htdocs\blog\index.php (12)
2016/09/09 18:35:46 [error] [php] Creating default object from empty value (C:\xampp\htdocs\blog\protected\controllers\UserController.php:47)
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CController.php(286): UserController->runAction()
#1 C:\xampp\htdocs\YII\framework\web\CController.php(265): UserController->runActionWithFilters()
#2 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): UserController->run()
#3 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\blog\index.php(12): CWebApplication->run()
REQUEST_URI=/blog/user/dettaglio
in C:\xampp\htdocs\blog\protected\controllers\UserController.php (47)
in C:\xampp\htdocs\blog\index.php (12)
2016/09/09 18:36:56 [error] [php] Creating default object from empty value (C:\xampp\htdocs\blog\protected\controllers\UserController.php:47)
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CController.php(286): UserController->runAction()
#1 C:\xampp\htdocs\YII\framework\web\CController.php(265): UserController->runActionWithFilters()
#2 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): UserController->run()
#3 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\blog\index.php(12): CWebApplication->run()
REQUEST_URI=/blog/user/dettaglio
in C:\xampp\htdocs\blog\protected\controllers\UserController.php (47)
in C:\xampp\htdocs\blog\index.php (12)
2016/09/09 18:37:09 [error] [php] Creating default object from empty value (C:\xampp\htdocs\blog\protected\controllers\UserController.php:47)
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CController.php(286): UserController->runAction()
#1 C:\xampp\htdocs\YII\framework\web\CController.php(265): UserController->runActionWithFilters()
#2 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): UserController->run()
#3 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\blog\index.php(12): CWebApplication->run()
REQUEST_URI=/blog/user/dettaglio
in C:\xampp\htdocs\blog\protected\controllers\UserController.php (47)
in C:\xampp\htdocs\blog\index.php (12)
2016/09/09 18:37:16 [error] [php] Creating default object from empty value (C:\xampp\htdocs\blog\protected\controllers\UserController.php:47)
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CController.php(286): UserController->runAction()
#1 C:\xampp\htdocs\YII\framework\web\CController.php(265): UserController->runActionWithFilters()
#2 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): UserController->run()
#3 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\blog\index.php(12): CWebApplication->run()
REQUEST_URI=/blog/user/dettaglio
in C:\xampp\htdocs\blog\protected\controllers\UserController.php (47)
in C:\xampp\htdocs\blog\index.php (12)
2016/09/11 10:13:38 [error] [php] Creating default object from empty value (C:\xampp\htdocs\blog\protected\controllers\UserController.php:47)
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CController.php(286): UserController->runAction()
#1 C:\xampp\htdocs\YII\framework\web\CController.php(265): UserController->runActionWithFilters()
#2 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): UserController->run()
#3 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\blog\index.php(12): CWebApplication->run()
REQUEST_URI=/blog/user/dettaglio
in C:\xampp\htdocs\blog\protected\controllers\UserController.php (47)
in C:\xampp\htdocs\blog\index.php (12)
2016/09/11 10:21:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested page does not exist.' in C:\xampp\htdocs\blog\protected\controllers\UserController.php:60
Stack trace:
#0 C:\xampp\htdocs\blog\protected\controllers\UserController.php(38): UserController->loadModel()
#1 C:\xampp\htdocs\YII\framework\web\actions\CInlineAction.php(49): UserController->actionDettaglio()
#2 C:\xampp\htdocs\YII\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 C:\xampp\htdocs\YII\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 C:\xampp\htdocs\YII\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): CController->run('dettaglio')
#6 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('user/dettaglio')
#7 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#8 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#9 {main}
REQUEST_URI=/blog/user/dettaglio
HTTP_REFERER=http://localhost/blog/user/3/Paolo
---
2016/09/11 10:22:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested page does not exist.' in C:\xampp\htdocs\blog\protected\controllers\UserController.php:60
Stack trace:
#0 C:\xampp\htdocs\blog\protected\controllers\UserController.php(38): UserController->loadModel()
#1 C:\xampp\htdocs\YII\framework\web\actions\CInlineAction.php(49): UserController->actionDettaglio()
#2 C:\xampp\htdocs\YII\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 C:\xampp\htdocs\YII\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 C:\xampp\htdocs\YII\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): CController->run('dettaglio')
#6 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('user/dettaglio')
#7 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#8 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#9 {main}
REQUEST_URI=/blog/user/dettaglio
HTTP_REFERER=http://localhost/blog/user/3/Paolo
---
2016/09/11 10:23:31 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested page does not exist.' in C:\xampp\htdocs\blog\protected\controllers\UserController.php:60
Stack trace:
#0 C:\xampp\htdocs\blog\protected\controllers\UserController.php(38): UserController->loadModel()
#1 C:\xampp\htdocs\YII\framework\web\actions\CInlineAction.php(49): UserController->actionDettaglio()
#2 C:\xampp\htdocs\YII\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 C:\xampp\htdocs\YII\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 C:\xampp\htdocs\YII\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): CController->run('dettaglio')
#6 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('user/dettaglio')
#7 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#8 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#9 {main}
REQUEST_URI=/blog/user/dettaglio
HTTP_REFERER=http://localhost/blog/user/3/Paolo
---
2016/09/11 10:23:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested page does not exist.' in C:\xampp\htdocs\blog\protected\controllers\UserController.php:60
Stack trace:
#0 C:\xampp\htdocs\blog\protected\controllers\UserController.php(38): UserController->loadModel()
#1 C:\xampp\htdocs\YII\framework\web\actions\CInlineAction.php(49): UserController->actionDettaglio()
#2 C:\xampp\htdocs\YII\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 C:\xampp\htdocs\YII\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 C:\xampp\htdocs\YII\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): CController->run('dettaglio')
#6 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('user/dettaglio')
#7 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#8 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#9 {main}
REQUEST_URI=/blog/user/dettaglio
---
2016/09/11 10:23:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested page does not exist.' in C:\xampp\htdocs\blog\protected\controllers\UserController.php:60
Stack trace:
#0 C:\xampp\htdocs\blog\protected\controllers\UserController.php(38): UserController->loadModel()
#1 C:\xampp\htdocs\YII\framework\web\actions\CInlineAction.php(49): UserController->actionDettaglio()
#2 C:\xampp\htdocs\YII\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 C:\xampp\htdocs\YII\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 C:\xampp\htdocs\YII\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): CController->run('dettaglio')
#6 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('user/dettaglio')
#7 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#8 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#9 {main}
REQUEST_URI=/blog/user/dettaglio
---
2016/09/11 10:24:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested page does not exist.' in C:\xampp\htdocs\blog\protected\controllers\UserController.php:60
Stack trace:
#0 C:\xampp\htdocs\blog\protected\controllers\UserController.php(38): UserController->loadModel()
#1 C:\xampp\htdocs\YII\framework\web\actions\CInlineAction.php(49): UserController->actionDettaglio()
#2 C:\xampp\htdocs\YII\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 C:\xampp\htdocs\YII\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 C:\xampp\htdocs\YII\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): CController->run('dettaglio')
#6 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('user/dettaglio')
#7 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#8 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#9 {main}
REQUEST_URI=/blog/user/dettaglio
HTTP_REFERER=http://localhost/blog/user/3/Paolo
---
2016/09/11 10:25:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested page does not exist.' in C:\xampp\htdocs\blog\protected\controllers\UserController.php:60
Stack trace:
#0 C:\xampp\htdocs\blog\protected\controllers\UserController.php(38): UserController->loadModel()
#1 C:\xampp\htdocs\YII\framework\web\actions\CInlineAction.php(49): UserController->actionDettaglio()
#2 C:\xampp\htdocs\YII\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 C:\xampp\htdocs\YII\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 C:\xampp\htdocs\YII\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): CController->run('dettaglio')
#6 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('user/dettaglio')
#7 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#8 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#9 {main}
REQUEST_URI=/blog/user/dettaglio
HTTP_REFERER=http://localhost/blog/user/3/Paolo
---
2016/09/11 10:28:31 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested page does not exist.' in C:\xampp\htdocs\blog\protected\controllers\UserController.php:56
Stack trace:
#0 C:\xampp\htdocs\blog\protected\controllers\UserController.php(38): UserController->loadModel()
#1 C:\xampp\htdocs\YII\framework\web\actions\CInlineAction.php(49): UserController->actionDettaglio()
#2 C:\xampp\htdocs\YII\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 C:\xampp\htdocs\YII\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 C:\xampp\htdocs\YII\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): CController->run('dettaglio')
#6 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('user/dettaglio')
#7 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#8 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#9 {main}
REQUEST_URI=/blog/user/dettaglio
HTTP_REFERER=http://localhost/blog/user/3/Paolo
---
2016/09/11 10:28:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested page does not exist.' in C:\xampp\htdocs\blog\protected\controllers\UserController.php:56
Stack trace:
#0 C:\xampp\htdocs\blog\protected\controllers\UserController.php(38): UserController->loadModel()
#1 C:\xampp\htdocs\YII\framework\web\actions\CInlineAction.php(49): UserController->actionDettaglio()
#2 C:\xampp\htdocs\YII\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 C:\xampp\htdocs\YII\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 C:\xampp\htdocs\YII\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): CController->run('dettaglio')
#6 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('user/dettaglio')
#7 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#8 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#9 {main}
REQUEST_URI=/blog/user/dettaglio
---
2016/09/11 10:30:18 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested page does not exist.' in C:\xampp\htdocs\blog\protected\controllers\PostController.php:183
Stack trace:
#0 C:\xampp\htdocs\blog\protected\controllers\PostController.php(48): PostController->loadModel()
#1 C:\xampp\htdocs\YII\framework\web\actions\CInlineAction.php(49): PostController->actionView()
#2 C:\xampp\htdocs\YII\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 C:\xampp\htdocs\YII\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#4 C:\xampp\htdocs\YII\framework\web\filters\CFilter.php(40): CFilterChain->run()
#5 C:\xampp\htdocs\YII\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#6 C:\xampp\htdocs\YII\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#7 C:\xampp\htdocs\YII\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\YII\framework\web\CController.php(291): CFilterChain->run()
#9 C:\xampp\htdocs\YII\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): CController->run('view')
#11 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('post/view')
#12 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#13 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#14 {main}
REQUEST_URI=/blog/post/view
---
2016/09/12 17:54:40 [error] [php] Invalid argument supplied for foreach() (C:\xampp\htdocs\YII\framework\web\helpers\CHtml.php:2525)
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CBaseController.php(126): require()
#1 C:\xampp\htdocs\YII\framework\web\CBaseController.php(95): UserController->renderInternal()
#2 C:\xampp\htdocs\YII\framework\web\CController.php(869): UserController->renderFile()
#3 C:\xampp\htdocs\YII\framework\web\CController.php(782): UserController->renderPartial()
#4 C:\xampp\htdocs\blog\protected\controllers\UserController.php(88): UserController->render()
#5 C:\xampp\htdocs\YII\framework\web\actions\CInlineAction.php(49): UserController->actionCreate()
#6 C:\xampp\htdocs\YII\framework\web\CController.php(308): CInlineAction->runWithParams()
#7 C:\xampp\htdocs\YII\framework\web\CController.php(286): UserController->runAction()
#8 C:\xampp\htdocs\YII\framework\web\CController.php(265): UserController->runActionWithFilters()
#9 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): UserController->run()
#10 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController()
#11 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#12 C:\xampp\htdocs\blog\index.php(12): CWebApplication->run()
REQUEST_URI=/blog/user/create
in C:\xampp\htdocs\blog\protected\views\user\create.php (30)
in C:\xampp\htdocs\blog\protected\controllers\UserController.php (88)
in C:\xampp\htdocs\blog\index.php (12)
2016/09/12 18:00:03 [error] [php] Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\blog\protected\controllers\UserController.php:81) (C:\xampp\htdocs\YII\framework\web\CHttpRequest.php:889)
Stack trace:
#0 C:\xampp\htdocs\blog\protected\controllers\UserController.php(83): UserController->redirect()
#1 C:\xampp\htdocs\YII\framework\web\actions\CInlineAction.php(49): UserController->actionCreate()
#2 C:\xampp\htdocs\YII\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 C:\xampp\htdocs\YII\framework\web\CController.php(286): UserController->runAction()
#4 C:\xampp\htdocs\YII\framework\web\CController.php(265): UserController->runActionWithFilters()
#5 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): UserController->run()
#6 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController()
#7 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#8 C:\xampp\htdocs\blog\index.php(12): CWebApplication->run()
REQUEST_URI=/blog/user/create
in C:\xampp\htdocs\blog\protected\controllers\UserController.php (83)
in C:\xampp\htdocs\blog\index.php (12)
2016/09/12 18:00:16 [error] [php] Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\blog\protected\controllers\UserController.php:81) (C:\xampp\htdocs\YII\framework\web\CHttpRequest.php:889)
Stack trace:
#0 C:\xampp\htdocs\blog\protected\controllers\UserController.php(83): UserController->redirect()
#1 C:\xampp\htdocs\YII\framework\web\actions\CInlineAction.php(49): UserController->actionCreate()
#2 C:\xampp\htdocs\YII\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 C:\xampp\htdocs\YII\framework\web\CController.php(286): UserController->runAction()
#4 C:\xampp\htdocs\YII\framework\web\CController.php(265): UserController->runActionWithFilters()
#5 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): UserController->run()
#6 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController()
#7 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#8 C:\xampp\htdocs\blog\index.php(12): CWebApplication->run()
REQUEST_URI=/blog/user/create
in C:\xampp\htdocs\blog\protected\controllers\UserController.php (83)
in C:\xampp\htdocs\blog\index.php (12)
2016/09/12 18:00:26 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "index".' in C:\xampp\htdocs\YII\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CController.php(270): CController->missingAction('')
#1 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(282): CController->run('')
#2 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('user')
#3 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#5 {main}
REQUEST_URI=/blog/user/
---
