2016/09/08 15:45:27 [error] [exception.CException] exception 'CException' with message 'CAssetManager.basePath "/Applications/XAMPP/xamppfiles/htdocs/blog/assets" is invalid. Please make sure the directory exists and is writable by the Web server process.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CAssetManager.php:138
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CAssetManager.php(123): CAssetManager->setBasePath('/Applications/X...')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CAssetManager.php(217): CAssetManager->getBasePath()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/zii/widgets/CListView.php(217): CAssetManager->publish('/Applications/X...')
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CBaseController.php(147): CListView->init()
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CBaseController.php(180): CBaseController->createWidget('zii.widgets.CLi...', Array)
#5 /Applications/XAMPP/xamppfiles/htdocs/blog/protected/views/post/index.php(9): CBaseController->widget('zii.widgets.CLi...', Array)
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CBaseController.php(126): require('/Applications/X...')
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CBaseController.php(95): CBaseController->renderInternal('/Applications/X...', Array, true)
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(869): CBaseController->renderFile('/Applications/X...', Array, true)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(782): CController->renderPartial('index', Array, true)
#10 /Applications/XAMPP/xamppfiles/htdocs/blog/protected/controllers/PostController.php(136): CController->render('index', Array)
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): PostController->actionIndex()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#13 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#14 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilter.php(40): CFilterChain->run()
#15 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#16 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#17 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#18 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(291): CFilterChain->run()
#19 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#20 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('')
#21 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('')
#22 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#23 /Applications/XAMPP/xamppfiles/htdocs/blog/index.php(11): CApplication->run()
#24 {main}
REQUEST_URI=/blog/
---
2016/09/08 15:45:46 [error] [exception.CException] exception 'CException' with message 'CAssetManager.basePath "/Applications/XAMPP/xamppfiles/htdocs/blog/assets" is invalid. Please make sure the directory exists and is writable by the Web server process.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CAssetManager.php:138
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CAssetManager.php(123): CAssetManager->setBasePath('/Applications/X...')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CAssetManager.php(217): CAssetManager->getBasePath()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/zii/widgets/CListView.php(217): CAssetManager->publish('/Applications/X...')
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CBaseController.php(147): CListView->init()
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CBaseController.php(180): CBaseController->createWidget('zii.widgets.CLi...', Array)
#5 /Applications/XAMPP/xamppfiles/htdocs/blog/protected/views/post/index.php(9): CBaseController->widget('zii.widgets.CLi...', Array)
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CBaseController.php(126): require('/Applications/X...')
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CBaseController.php(95): CBaseController->renderInternal('/Applications/X...', Array, true)
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(869): CBaseController->renderFile('/Applications/X...', Array, true)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(782): CController->renderPartial('index', Array, true)
#10 /Applications/XAMPP/xamppfiles/htdocs/blog/protected/controllers/PostController.php(136): CController->render('index', Array)
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): PostController->actionIndex()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#13 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#14 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilter.php(40): CFilterChain->run()
#15 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#16 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#17 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#18 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(291): CFilterChain->run()
#19 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#20 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('')
#21 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('')
#22 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#23 /Applications/XAMPP/xamppfiles/htdocs/blog/index.php(11): CApplication->run()
#24 {main}
REQUEST_URI=/blog/
---
2016/09/08 15:46:06 [error] [exception.CException] exception 'CException' with message 'CAssetManager.basePath "/Applications/XAMPP/xamppfiles/htdocs/blog/assets" is invalid. Please make sure the directory exists and is writable by the Web server process.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CAssetManager.php:138
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CAssetManager.php(123): CAssetManager->setBasePath('/Applications/X...')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CAssetManager.php(217): CAssetManager->getBasePath()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/zii/widgets/CListView.php(217): CAssetManager->publish('/Applications/X...')
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CBaseController.php(147): CListView->init()
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CBaseController.php(180): CBaseController->createWidget('zii.widgets.CLi...', Array)
#5 /Applications/XAMPP/xamppfiles/htdocs/blog/protected/views/post/index.php(9): CBaseController->widget('zii.widgets.CLi...', Array)
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CBaseController.php(126): require('/Applications/X...')
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CBaseController.php(95): CBaseController->renderInternal('/Applications/X...', Array, true)
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(869): CBaseController->renderFile('/Applications/X...', Array, true)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(782): CController->renderPartial('index', Array, true)
#10 /Applications/XAMPP/xamppfiles/htdocs/blog/protected/controllers/PostController.php(136): CController->render('index', Array)
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): PostController->actionIndex()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#13 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#14 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilter.php(40): CFilterChain->run()
#15 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#16 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#17 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#18 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(291): CFilterChain->run()
#19 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#20 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('')
#21 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('')
#22 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#23 /Applications/XAMPP/xamppfiles/htdocs/blog/index.php(11): CApplication->run()
#24 {main}
REQUEST_URI=/blog/
---
2016/09/08 15:46:08 [error] [exception.CException] exception 'CException' with message 'CAssetManager.basePath "/Applications/XAMPP/xamppfiles/htdocs/blog/assets" is invalid. Please make sure the directory exists and is writable by the Web server process.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CAssetManager.php:138
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CAssetManager.php(123): CAssetManager->setBasePath('/Applications/X...')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CAssetManager.php(217): CAssetManager->getBasePath()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/zii/widgets/CListView.php(217): CAssetManager->publish('/Applications/X...')
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CBaseController.php(147): CListView->init()
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CBaseController.php(180): CBaseController->createWidget('zii.widgets.CLi...', Array)
#5 /Applications/XAMPP/xamppfiles/htdocs/blog/protected/views/post/index.php(9): CBaseController->widget('zii.widgets.CLi...', Array)
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CBaseController.php(126): require('/Applications/X...')
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CBaseController.php(95): CBaseController->renderInternal('/Applications/X...', Array, true)
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(869): CBaseController->renderFile('/Applications/X...', Array, true)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(782): CController->renderPartial('index', Array, true)
#10 /Applications/XAMPP/xamppfiles/htdocs/blog/protected/controllers/PostController.php(136): CController->render('index', Array)
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): PostController->actionIndex()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#13 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#14 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilter.php(40): CFilterChain->run()
#15 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#16 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#17 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#18 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(291): CFilterChain->run()
#19 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#20 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('')
#21 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('')
#22 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#23 /Applications/XAMPP/xamppfiles/htdocs/blog/index.php(11): CApplication->run()
#24 {main}
REQUEST_URI=/blog/
---
2016/09/08 16:05:28 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:08:48 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:09:12 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:11:27 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:11:29 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:11:29 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:12:14 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:12:15 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:12:15 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:12:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:12:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:12:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:12:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:12:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:13:50 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:14:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:14:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:14:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:14:31 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:14:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:14:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:14:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:17:17 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:17:18 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:17:18 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:17:18 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:17:18 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:17:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:17:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:17:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:17:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:17:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:17:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:17:29 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:17:31 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:17:31 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:17:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:18:29 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii/default/login".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/default/log...')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii/default/login
---
2016/09/08 16:26:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii/default/login".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/default/log...')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii/default/login
---
2016/09/08 16:33:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:40:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:40:17 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:40:18 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:42:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:42:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:42:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:42:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:42:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:42:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:42:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:42:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:42:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:42:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:42:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
2016/09/08 16:42:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\YII\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YII\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\YII\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(12): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php/gii
---
